### ISSUE TITLE
javadoc location in wiki / tutorial for apis

### ISSUE THREAD

**Issue by kit-sunei** [EngineHub/WorldEditDocs#14]
https://worldedit.enginehub.org/en/latest/api/

on this page I believe a very positive addition would be to inform the user that your IDE can download the javadoc to use in-IDE, for you, with maven. This may be common knowledge, for some, but this is the first project / maven dependency that I learned about it. just having this knowledge (which i found by googling about javadoc support in the discord) allowed me to find the feature in eclipse, so I imagine a simple mention of it on the page about apis and documentation should be plenty sufficient.

sorry if this is unwanted feedback! hope it is helpful / informative, if it is wanted. I saw a good few questions of this in the discord, so it doesnt seem to just be me who would appreciate it, in the future

**Comment by wizjany** [comment]
I think a basic understanding of the Java environment is already expected when people are coming in and developing plugins. It's not really our place to teach people to use Java or their IDE here. there's plenty of other guides for that.

**Comment by kit-sunei** [comment]
fair enough, just figured i'd propose it, since i wasnt aware how much of this "should" be common knowledge, as I didn't know about it, despite doing code for a while, should I close it, then?

**Comment by wizjany** [comment]
dunno, that's just my opinion. there's other places in the docs where we tell people to use their IDE to do things and it's expected that the user knows how.
as far as javadocs, pretty sure that's a default feature for intellij if you're using a dependency management tool (eg maven/gradle) so it's more of an issue of eclipse making that feature "hidden" or people just not knowing how to use their IDE.

**Comment by octylFractal** [comment]
The javadocs have been hosted and linked for a while, https://github.com/EngineHub/WorldEditDocs/commit/3e7386d15e47588cd28881efb77cca7f44ff24aa.
