### ISSUE TITLE
Index in wrong place & a very tiny problem

### ISSUE THREAD

**Issue by SnowCutieOwO** [EngineHub/WorldEditDocs#49]
1. [usage/clipboard/](https://worldedit.enginehub.org/en/latest/usage/clipboard/):
* The two sub part of "Loading and Saving" now are the part of "Sharing" which is definitely not true
2. At [#7353c1c](https://github.com/EngineHub/WorldEditDocs/commit/7353c1cb7505e119b5b829b447658d443781b1fd), in line 133 column 175, there is a "`" lacked, and this caused the passage showed incorrectly.

**Comment by me4502** [comment]
I've fixed the first one, although I'm not sure what you mean by the last one? None of the files diffed in that commit have alterations on line 133

**Comment by SnowCutieOwO** [comment]
> I've fixed the first one, although I'm not sure what you mean by the last one? None of the files diffed in that commit have alterations on line 133
You see, this is the line 113:
```To share your current clipboard online, use ``//schem share``. You can also supply a name for the schematic, as well as an alternate upload destination and format using the →`←//schem share [name] [destination] [format]`` syntax.```
You could see at the arrow pointed position, there must be 2 ` instead of only one
I tried my best to describe it :XP:

**Comment by wizjany** [comment]
was fixed in d1f4e5d
