### ISSUE TITLE
Update tool / brush command references

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEditDocs#5]
This is now deprecated behavior, so let's stop suggesting it.
- [ ] Replace `/x` with `/tool x`
- [ ] Replace `/none` in a tool context with `/tool none`
- [ ] Replace `/none` in a brush context with `/brush none`
- [ ] Replace `/none` on the FAQ

**Comment by kees** [comment]
> * [ ]  Replace `/x` with `/tool x`
> * [ ]  Replace `/none` in a tool context with `/tool none`

These should be done now in 
https://github.com/EngineHub/WorldEditDocs/pull/16
